CC=gcc
CFLAGS = -g
test:	test.c
	$(CC) test.c -o test
s9:	s9.c
	$(CC) s9.c -o s9
s14: s14.c	
	$(CC) s14.c -o s14
s15: s15.c
	$(CC) s15.c -o s15		
s16:
	$(CC) $(CFLAGS) s16.c -o s16
s17:
	$(CC) $(CFLAGS) s17.c -o s17
fp18:
	$(CC) $(CFLAGS) fp18.c -o fp18		
s21:
	$(CC) $(CFLAGS) s21.c -o test
s23:
	$(CC) $(CFLAGS) s23.c -o test
clean:	
	del *.exe
