#!/bin/sh

# test for
for foo in bar fud 43; do
	echo $foo
done

for file in $(ls f*.sh); do
	lpr $file
done

# test when

echo "Enter your password"
read trythis
while [ "$trythis" != "secret" ]; do
	echo "Sorry, try again"
	read trythis
done


# test until
until who | grep "$1" > /dev/null
do
	sleep 60
done

# now ring the bell and announce the expected user.
echo -e '\a'
echo "**** $1 has just logged in ****"

exit 0